[package]
name = "polkavm-ffi"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
arbitrary = { version = "1.4.2", features = ["derive"] }

[dependencies.polkavm-common]
path = "../../crates/polkavm-common"
features = ["arbitrary"]
